[project]
name = "gds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "modelscope>=1.34.0",
    "transformers>=5.0.0",
]

[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "isort>=7.0.0",
    "ruff>=0.15.0",
]
